AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  QuizApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: backend/
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /submit
            Method: post
